CREATE TABLE PN(AMT MONEY)

INSERT INTO PN VALUES(1000), (-200), (3000), (-500), (5000), (-400)

SELECT * FROM PN

-- Write a query to show the positive and negative values in two differnet columns
WITH E AS
(SELECT AMT AS POS, ROW_NUMBER() OVER(ORDER BY AMT ASC) AS RNO FROM PN WHERE AMT>0),
F AS 
(SELECT AMT AS NEG, ROW_NUMBER() OVER(ORDER BY AMT DESC) AS RNO FROM PN WHERE AMT<0)
SELECT E.POS AS POS, F.NEG AS NEG FROM E INNER JOIN F ON E.RNO=F.RNO

