SELECT * FROM DEPT

SELECT LOC, LEN(LOC)
FROM DEPT
WHERE LEN(LOC) IN 
		((SELECT DISTINCT MIN(LEN(LOC)) FROM DEPT),
		(SELECT MAX(LEN(LOC)) FROM DEPT))
ORDER BY LOC ASC

SELECT TOP 1 LOC, LEN(LOC) FROM DEPT ORDER BY LEN(LOC) ASC, LOC ASC
UNION
SELECT TOP 1 LOC, LEN(LOC) FROM DEPT ORDER BY LEN(LOC) DESC, LOC ASC


SELECT LOC, LEN(LOC) FROM (SELECT TOP 1 LOC, LEN(LOC) FROM DEPT ORDER BY LEN(LOC) ASC, LOC ASC)
UNION ALL
SELECT LOC, LEN(LOC) FROM (SELECT TOP 1 LOC, LEN(LOC) FROM DEPT ORDER BY LEN(LOC) DESC, LOC ASC)

WITH ranked AS (
  SELECT 
      LOC,
      LEN(LOC) AS L,
      ROW_NUMBER() OVER (ORDER BY LEN(LOC) ASC,  LOC ASC)  AS rn_short,
      ROW_NUMBER() OVER (ORDER BY LEN(LOC) DESC, LOC ASC)  AS rn_long
  FROM DEPT
)
SELECT LOC, L
FROM ranked
WHERE rn_short = 1 OR rn_long = 1
ORDER BY L ASC, LOC ASC

WITH E AS
( SELECT LOC, LEN(LOC) AS L, ROW_NUMBER()OVER(ORDER BY LEN(LOC) ASC, LOC ASC) AS RN_S,
                        ROW_NUMBER()OVER(ORDER BY LEN(LOC) DESC, LOC ASC) AS RN_L
FROM DEPT )
SELECT LOC, L FROM E WHERE RN_S=1 OR RN_L=1 ORDER BY L ASC
